// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

interface IRootRegistry {
    function currentEpoch() external view returns (uint256);
    function currentRoot() external view returns (bytes32);
}

/// @title CheckpointVerifier
/// @notice Optional: lets any address verify their current-epoch Merkle proof onchain
///         and caches the result. Useful for hook integrations and access-gated features.
///
///         Leaf encoding (must match indexer's StandardMerkleTree — openzeppelin/merkle-tree):
///           keccak256(keccak256(abi.encode(
///             epoch, primaryWallet, linkedWallet1, linkedWallet2,
///             usernameHash, aura,
///             repResearch, repBuilder, repTrader, repLiquidity, repGovernance, repCommunity
///           )))
///
///         Types: [uint256, address, address, address, bytes32, uint256,
///                 int256, int256, int256, int256, int256, int256]
contract CheckpointVerifier {
    // -------------------------------------------------------------------------
    // Types
    // -------------------------------------------------------------------------

    struct UserCheckpoint {
        uint256 epoch;
        uint256 aura;
        int256 repResearch;
        int256 repBuilder;
        int256 repTrader;
        int256 repLiquidity;
        int256 repGovernance;
        int256 repCommunity;
    }

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    IRootRegistry public immutable rootRegistry;

    /// @notice Cached checkpoint per primary wallet (most recent verified epoch).
    mapping(address => UserCheckpoint) public checkpoints;

    // -------------------------------------------------------------------------
    // Events
    // -------------------------------------------------------------------------

    event CheckpointCached(
        address indexed profile, uint256 indexed epoch, uint256 aura
    );

    // -------------------------------------------------------------------------
    // Errors
    // -------------------------------------------------------------------------

    error InvalidProof();
    error StaleEpoch(uint256 provided, uint256 current);

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor(address _rootRegistry) {
        rootRegistry = IRootRegistry(_rootRegistry);
    }

    // -------------------------------------------------------------------------
    // External functions
    // -------------------------------------------------------------------------

    /// @notice Verify a Merkle proof for the current epoch and cache the result.
    ///
    /// @param primaryWallet  The profile's primary wallet (the leaf identity key).
    /// @param linkedWallet1  First linked wallet (address(0) if none).
    /// @param linkedWallet2  Second linked wallet (reserved, address(0) for now).
    /// @param usernameHash   keccak256 of the username string.
    /// @param aura           Aura value scaled by 1e18.
    /// @param rep            Packed REP by category [research, builder, trader, liq, gov, community].
    /// @param proof          Merkle proof siblings from the indexer.
    function verifyAndCache(
        address primaryWallet,
        address linkedWallet1,
        address linkedWallet2,
        bytes32 usernameHash,
        uint256 aura,
        int256[6] calldata rep,
        bytes32[] calldata proof
    ) external {
        uint256 epoch = rootRegistry.currentEpoch();
        bytes32 root = rootRegistry.currentRoot();

        // Only allow forward progression — prevents overwriting with stale data.
        uint256 cachedEpoch = checkpoints[primaryWallet].epoch;
        if (cachedEpoch != 0 && epoch <= cachedEpoch) revert StaleEpoch(epoch, cachedEpoch);

        // Reproduce the leaf hash as generated by StandardMerkleTree (double keccak256).
        bytes32 leaf = keccak256(
            bytes.concat(
                keccak256(
                    abi.encode(
                        epoch,
                        primaryWallet,
                        linkedWallet1,
                        linkedWallet2,
                        usernameHash,
                        aura,
                        rep[0],
                        rep[1],
                        rep[2],
                        rep[3],
                        rep[4],
                        rep[5]
                    )
                )
            )
        );

        if (!MerkleProof.verify(proof, root, leaf)) revert InvalidProof();

        checkpoints[primaryWallet] = UserCheckpoint({
            epoch: epoch,
            aura: aura,
            repResearch: rep[0],
            repBuilder: rep[1],
            repTrader: rep[2],
            repLiquidity: rep[3],
            repGovernance: rep[4],
            repCommunity: rep[5]
        });

        emit CheckpointCached(primaryWallet, epoch, aura);
    }

    /// @notice Read the cached Aura for a profile (returns 0 if never verified).
    function getAura(address profile) external view returns (uint256) {
        return checkpoints[profile].aura;
    }

    /// @notice Read the cached total REP for a profile in a specific category.
    function getRep(address profile, uint8 category) external view returns (int256) {
        UserCheckpoint storage cp = checkpoints[profile];
        if (category == 0) return cp.repResearch;
        if (category == 1) return cp.repBuilder;
        if (category == 2) return cp.repTrader;
        if (category == 3) return cp.repLiquidity;
        if (category == 4) return cp.repGovernance;
        if (category == 5) return cp.repCommunity;
        return 0;
    }
}
